---
version: "3.7"
services:
  app:
    image: datagov/ckanext-usmetadata:${CKAN_VERSION}
    build:
      context: .
      args:
        CKAN_VERSION: ${CKAN_VERSION}
    env_file:
      - .env
    environment:
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_DATAPUSHER_URL: http://localhost:8080/  # datapusher is not really enabled
      CKAN__PLUGINS: usmetadata
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - .:/app
      - ckan_storage:/var/lib/ckan
  db:
    image: ckan/ckan-postgres-dev:${CKAN_VERSION}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  solr:
    image: datagov/catalog.data.gov.solr:latest
    ports:
      - "8983:8983"

volumes:
  ckan_storage:
  pg_data:
  solr_data:
